import Link from 'next/link';

import { LEGAL_EFFECTIVE_DATE, merchantDetails } from '@/lib/legal/merchant';

export default function CustomerInformationPage() {
  return (
    <article className="space-y-8">
      <div><p className="text-sm font-medium text-emerald-700">Customer information</p><h1 className="mt-2 text-3xl font-semibold">Who you are paying and what you receive</h1><p className="mt-3 text-slate-600">Effective {LEGAL_EFFECTIVE_DATE}</p></div>
      <section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Merchant identity</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-[10rem_1fr]"><dt className="text-slate-500">Official name</dt><dd>{merchantDetails.legalName}</dd><dt className="text-slate-500">Trading name</dt><dd>{merchantDetails.tradingName}</dd><dt className="text-slate-500">Address</dt><dd>{merchantDetails.address}</dd><dt className="text-slate-500">Customer support</dt><dd><a className="text-emerald-700 hover:underline" href={`mailto:${merchantDetails.supportEmail}`}>{merchantDetails.supportEmail}</a>{merchantDetails.supportPhone ? ` · ${merchantDetails.supportPhone}` : ''}</dd></dl></section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Service and delivery</h2><p>StockIntel Agri is subscription software for agricultural inventory, field operations, team access, packhouse activity, expenses, weather records, livestock, disease scouting, and reporting. It does not sell or deliver physical farm goods through the subscription checkout.</p><p>Paid digital features are enabled in the customer’s workspace only after Paystack confirms a successful payment and the amount, currency, plan, and transaction reference match our order. Access is normally available immediately after verification. If verification is delayed, contact support with the Paystack reference shown on the billing page.</p></section>
      <section className="space-y-3"><h2 className="text-xl font-semibold">Payments and responsibility</h2><p>Paystack securely processes the payment. StockIntel does not collect or store full card numbers, PINs, or CVVs. {merchantDetails.legalName}, not Paystack, is responsible for the StockIntel subscription, service delivery, customer support, refunds, and dispute resolution.</p><p>Recurring plans renew at the interval and amount displayed before checkout until cancelled. A free trial does not initiate a charge by itself.</p></section>
      <section className="grid gap-4 sm:grid-cols-3"><Link className="rounded-xl border bg-white p-5 hover:border-emerald-500" href="/legal/terms"><h2 className="font-semibold">Terms of service</h2><p className="mt-2 text-sm text-slate-600">Subscription, acceptable use, warranties, and customer responsibilities.</p></Link><Link className="rounded-xl border bg-white p-5 hover:border-emerald-500" href="/legal/privacy"><h2 className="font-semibold">Privacy policy</h2><p className="mt-2 text-sm text-slate-600">What data is used, why it is used, and who receives it.</p></Link><Link className="rounded-xl border bg-white p-5 hover:border-emerald-500" href="/legal/refunds"><h2 className="font-semibold">Refunds & cancellation</h2><p className="mt-2 text-sm text-slate-600">How to cancel, request a refund, or report a duplicate charge.</p></Link></section>
    </article>
  );
}
